fix: install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -292,7 +292,7 @@ if [[ "$GO_MODE" == "true" ]]; then
     echo "Archiving all builds into a single archive..."
     GO_ARCHIVE_NAME="backend_build.zip"
     
-    if [ ! -f ".env.example" ]; then
+    if [ ! -f ".env" ]; then
         echo "Error: .env.example not found. Cannot create archive."
         exit 1
     fi
@@ -306,7 +306,7 @@ if [[ "$GO_MODE" == "true" ]]; then
     cp ./build/* "$BUILD_DIR/"
     cp -r docs "$BUILD_DIR/"
     cp -r assets "$BUILD_DIR/"
-    cp .env.example "$BUILD_DIR/.env"
+    cp .env "$BUILD_DIR/.env"
     cp -r migrations "$BUILD_DIR/"
     if [ -f "fill_db.sql" ]; then
       cp fill_db.sql "$BUILD_DIR/"
@@ -363,7 +363,7 @@ if [[ "$GO_DOCKER_MODE" == "true" ]]; then
   docker compose down > /dev/null 2>&1
   if [[ "$CLEAR_MODE" == "true" ]]; then
     docker compose down > /dev/null 2>&1
-    docker volume rm electronicqueue_db-data > /dev/null 2>&1
+    docker volume rm eq_lesnaya_db-data > /dev/null 2>&1
   fi
   if [[ "$FILL" == "true" ]]; then
     echo "Copying fill_db.sql to migrations/ for Docker..."
@@ -396,7 +396,7 @@ fi
 
 if [[ "$FLUTTER_MODE" == "true" ]]; then
   echo "--- Flutter Frontend Setup ---"
-  cd "$(dirname "$0")/../electronicqueue-frontend" || { echo "Failed to change directory to electronicqueue-frontend."; exit 1; }
+  cd "$(dirname "$0")/../eqLesnaya-front" || { echo "Failed to change directory to eqLesnaya-front."; exit 1; }
   
   # Generate .env for Flutter frontend
   FLUTTER_ENV_FILE=".env"
@@ -476,13 +476,13 @@ if [[ "$FLUTTER_MODE" == "true" ]]; then
 fi
 
 if [[ "$FLUTTER_DOCKER_MODE" == "true" ]]; then
-  cd "$(dirname "$0")/../electronicqueue-frontend" || { echo "Failed to change directory to electronicqueue-frontend."; exit 1; }
+  cd "$(dirname "$0")/../eqLesnaya-front" || { echo "Failed to change directory to eqLesnaya-front."; exit 1; }
   if ! docker info > /dev/null 2>&1; then
     echo "Make sure that Docker Engine is running. Try restarting Docker Desktop."
     exit 1
   fi
   docker compose down > /dev/null 2>&1
-  cd "$(dirname "$0")/../electronicqueue-frontend/lib" || { echo "lib directory not found!"; exit 1; }
+  cd "$(dirname "$0")/../eqLesnaya-front/lib" || { echo "lib directory not found!"; exit 1; }
   mapfile -t FLUTTER_MAIN_FILES < <(find . -maxdepth 2 -mindepth 2 -type f -name '*main*.dart' | sed 's|^./||')
   cd - > /dev/null 2>&1
   FLUTTER_ENV_FILE=".env"
@@ -522,7 +522,7 @@ EOF
     BASE_HREF_PATH=$(basename "$MAIN_FILE" .dart | sed 's/^main_//')
     BASE_HREF_VALUE="/${BASE_HREF_PATH}/"
     PORT=$((FRONTEND_PORT + INDEX))
-    CONTAINER_NAME="electronicqueue_${SERVICE_NAME}"
+    CONTAINER_NAME="eqLesnaya_${SERVICE_NAME}"
     echo "  $SERVICE_NAME:" >> $COMPOSE_FILE
     echo "    build:" >> $COMPOSE_FILE
     echo "      context: ." >> $COMPOSE_FILE
