refactor: scripts

diff --git a/run b/run
--- a/run
+++ b/run
@@ -7,7 +7,7 @@ set +o allexport
 
 # Автоматический поиск main файлов Flutter frontend
 cd "$(dirname "$0")" && docker compose down > /dev/null 2>&1
-cd "$(dirname "$0")/../electronicqueue-frontend" && docker compose down > /dev/null 2>&1
+cd "$(dirname "$0")/../eqLesnaya-front" && docker compose down > /dev/null 2>&1
 cd - > /dev/null > /dev/null 2>&1
 
 # Kill processes on BACKEND_PORT, FRONTEND_PORT
@@ -98,7 +98,7 @@ if { [[ "$RUN_GO" == "true" && -n "$BACKEND_PORT" ]] || [[ "$RUN_GO_DOCKER" == "
   kill_by_port $BACKEND_PORT
 fi
 if { [[ "$RUN_FLUTTER" == "true" && -n "$FRONTEND_PORT" ]] || [[ "$RUN_FLUTTER_DOCKER" == "true" && -n "$FRONTEND_PORT" ]]; }; then
-  cd "$(dirname "$0")/../electronicqueue-frontend/lib" || { echo "lib directory not found!"; exit 1; }
+  cd "$(dirname "$0")/../eqLesnaya-front/lib" || { echo "lib directory not found!"; exit 1; }
   mapfile -t FLUTTER_MAIN_FILES < <(find . -maxdepth 2 -mindepth 2 -type f -name '*main*.dart' | sed 's|^./||')
   cd - > /dev/null 2>&1
   N=${#FLUTTER_MAIN_FILES[@]}
@@ -144,7 +144,7 @@ fi
 
 # Run Flutter frontend
 if [[ "$RUN_FLUTTER" == "true" ]]; then
-  cd "$(dirname "$0")/../electronicqueue-frontend" || { echo "Failed to change directory to electronicqueue-frontend."; exit 1; }
+  cd "$(dirname "$0")/../eqLesnaya-front" || { echo "Failed to change directory to eqLesnaya-front."; exit 1; }
   if flutter pub get; then
     echo "Flutter setup complete."
   else
@@ -168,7 +168,7 @@ if [[ "$RUN_FLUTTER" == "true" ]]; then
 
 elif [[ "$RUN_FLUTTER_DOCKER" == "true" ]]; then
   echo "Starting Flutter frontend containers from compose.yaml..."
-  cd "$(dirname "$0")/../electronicqueue-frontend" || { echo "Failed to change directory to electronicqueue-frontend."; exit 1; }
+  cd "$(dirname "$0")/../eqLesnaya-front" || { echo "Failed to change directory to eqLesnaya-front."; exit 1; }
   if ! docker info > /dev/null 2>&1; then
     echo "Make sure that Docker Engine is running. Try restarting Docker Desktop."
     exit 1
diff --git a/uninstall b/uninstall
--- a/uninstall
+++ b/uninstall
@@ -81,7 +81,7 @@ if [[ "$GO" == "true" ]]; then
 fi
 
 if [[ "$FLUTTER" == "true" ]]; then
-  cd "$(dirname "$0")/../electronicqueue-frontend" || { echo "Failed to change directory to electronicqueue-frontend."; exit 1; }
+  cd "$(dirname "$0")/../eqLesnaya-front" || { echo "Failed to change directory to eqLesnaya-front."; exit 1; }
   echo "Cleaning Flutter project..."
   if flutter clean; then
     echo "Flutter project cleaned."
@@ -108,7 +108,7 @@ fi
 
 if [[ "$FLUTTER_DOCKER" == "true" ]]; then
   echo "Full cleanup for Flutter: containers, images, volumes, orphans..."
-  cd "$(dirname "$0")/../electronicqueue-frontend" || { echo "Failed to change directory to electronicqueue-frontend."; exit 1; }
+  cd "$(dirname "$0")/../eqLesnaya-front" || { echo "Failed to change directory to eqLesnaya-front."; exit 1; }
   if ! docker info > /dev/null 2>&1; then
     echo "Make sure that Docker Engine is running. Try restarting Docker Desktop."
     exit 1
